### PR TITLE
Remove warning in python3.8

### LINKED ISSUE #30: DeprecationWarning on Python 3.8+
Python 3.8 and above show the following warning while running the tests:

```python
/.../zope/index/text/okapiindex.py:347: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  score(result, items, docid2len, idf, meandoclen)
```

`score` seems to be implemented in `C`, so it is not clear to me which auf the parameters is implicitly converted.

### PR DESCRIPTION
**Pull request by Recursing**
I think we can just change this, can't think of any downside and our tests pass without warnings

Fixes #30

### CODE REVIEW

**Review by jamadden — APPROVED** [review]
This does fix the warning, and the tests pass. 

I'm slightly concerned that the original author's intent, the intent of the algorithm, was to truncate the *doclen* floating point value to just its integral component (given `1.9`, `PyInt_AsLong` and `PyLong_AsLong` would produce `1`). If the author wanted to use a floating point value in that computation, they could have used `PyFloat_AsDouble` to start with: that API has existed [since at least 2.4](https://docs.python.org/2.4/api/floatObjects.html). Maybe this sub-expression should be cast to an `int`?

But again, the tests pass, so I'm not too worried about it. I just think we need to leave a prominent change note that text scores may change with this version.

**Comment by Recursing** [comment]
🤔 those are good points.

I can't think of any potential reason to truncate that value.
As for why the author used `PyLong_AsLong ` I think that before 5d83b49a7c7eb8f291bea9911fd720ab2f9bdc0e that value was an integer, and the C code maybe was just never updated to reflect the change, since it seems from d043e4a25d1de56d0c7c6ece8c78aead56a066c8 that it was originally in a different repository?

Looking at https://github.com/zopefoundation/zope.index/blob/5d182f2547b8cad270cbc4e1a1e7eddb51697d2c/src/zope/index/text/okapiindex.py#L371-L376 it seems that the value is always guaranteed to be an integer that gets stored as a float in the IFBtree, like mentioned in #30.
Unless of course someone is using the `score` function directly or overriding `_get_frequencies` or `_docweight`

**Comment by d-maurer** [comment]
Lorenzo wrote at 2021-10-1 10:19 -0700:
>I can't think of any potential reason to truncate that value.

In some cases, truncation may be usefull for indexing -- to
reduce the index size (number of index values).

**Comment by Recursing** [comment]
> In some cases, truncation may be useful for indexing

I don't think that's the case here.

Also, if I understand correctly, this warning will become an error in the just released python3.10, https://github.com/python/cpython/commit/20941de0ddc39ce9f07e29b4cc770e8a9ef14d41 so it's going to be more than a mild annoyance.
I wonder if we should change also https://github.com/zopefoundation/zope.index/blob/140f9a56d9bb26e5b694b3ba381a9f24a9f8ac75/src/zope/index/text/okascore.c#L93

**Comment by icemac** [comment]
Python 3.10 seems to break on the issue fixed here.
What has to be done to get this PR merged?

**Comment by icemac** [comment]
Are there any new ideas about this PR? It seems to be needed to get zope.index and zc.catalog to Python 3.10.

**Comment by icemac** [comment]
Thank you for this PR and the review. 😃
I just merged it as it seems to make the tests for Python 3.10 happy.

**Pull request merged**
