### PR TITLE
CI for travis and appveyor

### PR DESCRIPTION
**Pull request by fgregg**
Attn @tseaver and @mgedmin

### CODE REVIEW

**Comment by tseaver** [comment]
LGTM.  @mgedmin do you want to enable the appveyor webhook, and have @fgregg push a trivial commit to test it?

**Comment by mgedmin** [comment]
There are two problems with using my personal Appveyor account for ZopeFoundation stuff:
- I have to be the one who does things
- I get email for every build status change (which I want for my personal projects, but not all of ZF thank you)

Can we come up with a better solution?

**Comment by fgregg** [comment]
Hi @mgedmin , I don't know if you want to defer setting up an appveyor account until you find a better solution.

If you wanted to proceed, then you need to
- [ ] set up appveyor
- [ ] provide a new secure pypi password for the travis.yml file

**Comment by mgedmin** [comment]
```
  secure: "BEJhxAItA0fMiDS+2fV6VhoiTMXDuhWbVRpmjr3IhyMI4BSNRGVE46qvGY78/30reXMbvvEvmUPFhq4yLhq0O4UAgOis8318ramt9AoJLOtIkFTydytOysY9RZ2dDdFWRmpcFQ7K8xrasoJKZQRRGtbgIZ6hGtp1b4K3clNKaJ8="
```

**Comment by mgedmin** [comment]
I've created https://ci.appveyor.com/project/mgedmin/zope-index

**Comment by fgregg** [comment]
This is ready to merge. Don't forget to add `zope.wheelbuilder` as a maintainer on pypi.

**Comment by mgedmin** [comment]
Thank you for the reminder -- I completely forgot about PyPI roles ;)

**Comment by fgregg** [comment]
@tseaver @mgedmin do you want to cut a new release to get the wheels on pypi?

**Comment by tseaver** [comment]
I just tagged and pushed 4.2.0:

  https://pypi.python.org/pypi/zope.index/4.2.0

**Comment by fgregg** [comment]
Thank you @tseaver and @mgedmin! Now Mac and Window can now install my library https://github.com/datamade/dedupe without a compiler.  Thank you for working with me on getting all these wheels built.

**Comment by tseaver** [comment]
Thank you @fgregg for all the patches!

**Pull request merged**
